-- MySQL Script generated by MySQL Workbench
-- Wed Mar  1 11:55:55 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Users` (
  `_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `country` VARCHAR(45) NULL,
  `gender` VARCHAR(45) NULL,
  `birth_date` DATE NULL,
  `zip_code` INT NULL,
  `subs_channels_id` INT NULL,
  `comments_id` INT NOT NULL,
  PRIMARY KEY (`_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Likes_list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Likes_list` (
  `_id` INT NOT NULL,
  `Users__id` INT NOT NULL,
  `timeStamp` TIMESTAMP NULL,
  PRIMARY KEY (`_id`, `Users__id`),
  UNIQUE INDEX `_id_UNIQUE` (`_id` ASC) VISIBLE,
  INDEX `fk_Likes_list_Users1_idx` (`Users__id` ASC) VISIBLE,
  CONSTRAINT `fk_Likes_list_Users1`
    FOREIGN KEY (`Users__id`)
    REFERENCES `mydb`.`Users` (`_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`dislikes_list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`dislikes_list` (
  `_id` INT NOT NULL,
  `Users__id` INT NOT NULL,
  `timeStamp` TIMESTAMP NULL,
  PRIMARY KEY (`_id`, `Users__id`),
  UNIQUE INDEX `_id_UNIQUE` (`_id` ASC) INVISIBLE,
  INDEX `fk_dislikes_list_Users1_idx` (`Users__id` ASC) VISIBLE,
  CONSTRAINT `fk_dislikes_list_Users1`
    FOREIGN KEY (`Users__id`)
    REFERENCES `mydb`.`Users` (`_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tags_list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tags_list` (
  `_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`_id`),
  UNIQUE INDEX `_id_UNIQUE` (`_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`likes_comments_list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`likes_comments_list` (
  `_id` INT NOT NULL,
  `Users_id` INT NOT NULL,
  `timeStamp` TIMESTAMP NULL,
  PRIMARY KEY (`_id`, `Users_id`),
  UNIQUE INDEX `_id_UNIQUE` (`_id` ASC) VISIBLE,
  INDEX `fk_likes_comments_list_Users1_idx` (`Users_id` ASC) VISIBLE,
  CONSTRAINT `fk_likes_comments_list_Users1`
    FOREIGN KEY (`Users_id`)
    REFERENCES `mydb`.`Users` (`_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`dislikes_comments_list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`dislikes_comments_list` (
  `_id` INT NOT NULL,
  `Users_id` INT NOT NULL,
  `timeStamp` TIMESTAMP NULL,
  PRIMARY KEY (`_id`, `Users_id`),
  UNIQUE INDEX `_id_UNIQUE` (`_id` ASC) VISIBLE,
  INDEX `fk_dislikes_comments_list_Users1_idx` (`Users_id` ASC) VISIBLE,
  CONSTRAINT `fk_dislikes_comments_list_Users1`
    FOREIGN KEY (`Users_id`)
    REFERENCES `mydb`.`Users` (`_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Comments` (
  `_id` INT NOT NULL,
  `text` VARCHAR(45) NULL,
  `timeStamp` TIMESTAMP NULL,
  `likes` INT NOT NULL,
  `dislikes` INT NOT NULL,
  `Users__id` INT NOT NULL,
  PRIMARY KEY (`_id`, `Users__id`),
  UNIQUE INDEX `_id_UNIQUE` (`_id` ASC) VISIBLE,
  INDEX `fk_Comments_likes_comments_list1_idx` (`likes` ASC) VISIBLE,
  INDEX `fk_Comments_dislikes_comments_list1_idx` (`dislikes` ASC) VISIBLE,
  INDEX `fk_Comments_Users1_idx` (`Users__id` ASC) VISIBLE,
  CONSTRAINT `fk_Comments_likes_comments_list1`
    FOREIGN KEY (`likes`)
    REFERENCES `mydb`.`likes_comments_list` (`_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comments_dislikes_comments_list1`
    FOREIGN KEY (`dislikes`)
    REFERENCES `mydb`.`dislikes_comments_list` (`_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comments_Users1`
    FOREIGN KEY (`Users__id`)
    REFERENCES `mydb`.`Users` (`_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Videos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Videos` (
  `_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `desc` VARCHAR(45) NULL,
  `size` INT NULL,
  `name_vid` VARCHAR(45) NULL,
  `lenght_vid` INT NULL,
  `thumbnail` VARCHAR(45) NULL,
  `state` VARCHAR(45) NULL,
  `upload_time` TIMESTAMP NULL,
  `play_num` INT NULL,
  `total_likes` INT NULL,
  `total_dislikes` INT NULL,
  `likes` INT NOT NULL,
  `dislikes` INT NOT NULL,
  `tags` INT NOT NULL,
  `comments` INT NOT NULL,
  `Users__id` INT NOT NULL,
  PRIMARY KEY (`_id`, `Users__id`),
  INDEX `fk_Videos_Likes_list1_idx` (`likes` ASC) VISIBLE,
  INDEX `fk_Videos_dislikes_list1_idx` (`dislikes` ASC) VISIBLE,
  INDEX `fk_Videos_tags_list1_idx` (`tags` ASC) VISIBLE,
  INDEX `fk_Videos_Comments1_idx` (`comments` ASC) VISIBLE,
  INDEX `fk_Videos_Users1_idx` (`Users__id` ASC) VISIBLE,
  CONSTRAINT `fk_Videos_Likes_list1`
    FOREIGN KEY (`likes`)
    REFERENCES `mydb`.`Likes_list` (`_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Videos_dislikes_list1`
    FOREIGN KEY (`dislikes`)
    REFERENCES `mydb`.`dislikes_list` (`_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Videos_tags_list1`
    FOREIGN KEY (`tags`)
    REFERENCES `mydb`.`tags_list` (`_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Videos_Comments1`
    FOREIGN KEY (`comments`)
    REFERENCES `mydb`.`Comments` (`_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Videos_Users1`
    FOREIGN KEY (`Users__id`)
    REFERENCES `mydb`.`Users` (`_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Channels`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Channels` (
  `_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `desc` VARCHAR(45) NULL,
  `date_creation` DATE NULL,
  `Users_id` INT NOT NULL,
  PRIMARY KEY (`_id`, `Users_id`),
  INDEX `fk_Channels_Users1_idx` (`Users_id` ASC) VISIBLE,
  CONSTRAINT `fk_Channels_Users1`
    FOREIGN KEY (`Users_id`)
    REFERENCES `mydb`.`Users` (`_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Playlists`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Playlists` (
  `_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `isPublic` TINYINT NULL,
  `creation_date` DATE NULL,
  `Users__id` INT NOT NULL,
  PRIMARY KEY (`_id`, `Users__id`),
  INDEX `fk_Playlists_Users1_idx` (`Users__id` ASC) VISIBLE,
  CONSTRAINT `fk_Playlists_Users1`
    FOREIGN KEY (`Users__id`)
    REFERENCES `mydb`.`Users` (`_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Users_subscribes_Channels`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Users_subscribes_Channels` (
  `Users__id` INT NOT NULL,
  `Channels__id` INT NOT NULL,
  PRIMARY KEY (`Users__id`, `Channels__id`),
  INDEX `fk_Users_has_Channels_Channels1_idx` (`Channels__id` ASC) VISIBLE,
  INDEX `fk_Users_has_Channels_Users1_idx` (`Users__id` ASC) VISIBLE,
  CONSTRAINT `fk_Users_has_Channels_Users1`
    FOREIGN KEY (`Users__id`)
    REFERENCES `mydb`.`Users` (`_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Users_has_Channels_Channels1`
    FOREIGN KEY (`Channels__id`)
    REFERENCES `mydb`.`Channels` (`_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Playlists_has_videos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Playlists_has_videos` (
  `Videos_id` INT NOT NULL,
  `Playlists_id` INT NOT NULL,
  PRIMARY KEY (`Videos_id`, `Playlists_id`),
  INDEX `fk_Videos_has_Playlists_Playlists1_idx` (`Playlists_id` ASC) VISIBLE,
  INDEX `fk_Videos_has_Playlists_Videos1_idx` (`Videos_id` ASC) VISIBLE,
  CONSTRAINT `fk_Videos_has_Playlists_Videos1`
    FOREIGN KEY (`Videos_id`)
    REFERENCES `mydb`.`Videos` (`_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Videos_has_Playlists_Playlists1`
    FOREIGN KEY (`Playlists_id`)
    REFERENCES `mydb`.`Playlists` (`_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
